### ISSUE TITLE
После установки при попытке запустить любую команду, например bitrix create - ошибка

### ISSUE THREAD

**Issue by dimaaxxy** [bitrix-tools/cli#31]
`[root@sgmk assets]# bitrix create
/usr/lib/node_modules/@bitrix/cli/bin/bitrix:9
updateNotifier({pkg, ...pkg}).notify({
                     ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
`

**Comment by dimaaxxy** [comment]
Друзья, у кого такая же проблема, посмотрите в сторону обновления nodejs, на версии 10 всё запустилось, по умолчанию почему-то установлена была 6 версия
