### ISSUE TITLE
В Windows 11 build вызывает RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PrOpOvEdNiK** [bitrix-tools/cli#56]
node -v - 19.3.0 (другие пробовал. разные. на старых - ошибка gcc. на 16+ вот эта получается)
npm -v - 9.2.0

Попытка собрать свежесозданный через `bitrix create` пустой экстеншен:
bitrix build -p ./test
вызывает
```ps
PS C:\www\_front\bitrix-cli\local\js> bitrix build -p ./test
node:fs:283
function existsSync(path) {
                   ^

RangeError: Maximum call stack size exceeded
    at Object.existsSync (node:fs:283:20)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:36:12)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)
    at getTargets (C:\ProgramData\nvm\v19.3.0\node_modules\@bitrix\cli\dist\bitrix.build.js:46:16)

Node.js v19.3.0
```

В среде WSL этот же экстеншен с примерно тем же node собирается успешно
```bash
bsv@NYX-MSI-RAIDER:/mnt/c/www/_front/bitrix-cli/local/js$ bitrix build -p ./test
✔ 11:14:03 Build extension test..mnt.c.www._front.bitrix-cli.local.js.test  js: 1 KB
bsv@NYX-MSI-RAIDER:/mnt/c/www/_front/bitrix-cli/local/js$ node -v
v19.0.0
bsv@NYX-MSI-RAIDER:/mnt/c/www/_front/bitrix-cli/local/js$ npm -v
8.19.2
```

**Comment by 13Hz** [comment]
Попробуйте node v10.24.1 и npm 6.14.12

Такая же ошибка была на рекомендуемых версиях из документации. Система Windows 10

**Comment by afonja14755** [comment]
Windows 10;
node -v - 10.21.1;
npm -v - 6.14.12;
Проверял также на 10.22.1, 16.17.1, 18.12.1, 18.14.0 через nvm.

Абсолютно такая же проблема на всех выше указанных версиях.

Честно говоря не представляю как ребята вообще тестируют это.
Если есть у кого ссылка на страницу где описаны версии, поделитесь.

**Comment by PrOpOvEdNiK** [comment]
> Попробуйте node v10.24.1 и npm 6.14.12
> Такая же ошибка была на рекомендуемых версиях из документации. Система Windows 10

Ниже чем на 16, говорю же, происходят ошибки gcc и версии Visual Studio.

**Comment by PrOpOvEdNiK** [comment]
> browserslist: true - удалите эту строку, они что-то напортачили с ней.

Это помогло. Спасибо!
