### ISSUE TITLE
Error: spawn E2BIG

### ISSUE THREAD

**Issue by Suntechnic** [bitrix-tools/cli#57]
После обновления до версии **3.2.0**

Возникает ошибка:
```
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at UpdateNotifier.check (/usr/lib/node_modules/@bitrix/cli/node_modules/update-notifier/index.js:96:3)
    at module.exports.options (/usr/lib/node_modules/@bitrix/cli/node_modules/update-notifier/index.js:151:17)
    at Object.<anonymous> (/usr/lib/node_modules/@bitrix/cli/bin/bitrix:9:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Ошибка появляется не сразу после обновления, что интересно. **3.1.1** рабочая.

https://qna.habr.com/q/1264582

```
# npm --versions
{ npm: '6.14.12',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.4',
  icu: '64.2',
  modules: '64',
  napi: '7',
  nghttp2: '1.41.0',
  node: '10.24.1',
  openssl: '1.1.1k',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '6.8.275.32-node.59',
  zlib: '1.2.11' }
```

**Comment by vovkabelov** [comment]
@Suntechnic, здравствуйте. Обновитесь, пожалуйста до @bitrix/cli v3.2.1, должно помочь

**Comment by Suntechnic** [comment]
Теперь вроде сборка работает но в начале выдает такую ошибку: 
```
~> bitrix build --path=/home/bitrix/www/local/js/ --watch
(node:54992) UnhandledPromiseRejectionWarning: Error: Not supported
    at Object.<anonymous> (/usr/lib/node_modules/@bitrix/cli/bin/bitrix:8:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:54992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:54992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vovkabelov** [comment]
@Suntechnic, обновитесь еще раз. До v3.2.2, проблем больше быть не должно
