### ISSUE TITLE
Не собираются модули  Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by Voral** [bitrix-tools/cli#62]
Две недели не пользовался утилитой. Сегодня не собирается ни один модуль. За это время скорее всего обновлял npm и node. 

Воспроизводится на всех пакетах. Для эксперимента создал новый  bitrix create...

Запускаю   "bitrix build"  получаю ошибку (такая же и остальных)

` ✖ 09:59:46 Build extension vasoft.coupon  
/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:489
    throw new Error(error);
          ^

Error: TypeError: Cannot read properties of undefined (reading 'reduce')
    at printError (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:489:11)
    at report (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:554:5)
    at buildDirectory (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:901:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async build (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:922:5)
    at async bitrixBuild (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:1069:3)

Node.js v18.3.0
`

npm 8.11.0
yarn 1.22.19

**Comment by Voral** [comment]
Вывел error на строке 550 /usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js

`
TypeError: Cannot read properties of undefined (reading 'reduce')
    at getGlobals (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:719:18)
    at rollupBundle (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:794:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildDirectory (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:892:22)
    at async build (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:923:5)
    at async bitrixBuild (/usr/lib/node_modules/@bitrix/cli/dist/bitrix.build.js:1070:3)
`

**Comment by Voral** [comment]
На ноде 17.9 сборка происходит
